### ISSUE TITLE
Could It also clear mesos tmp files?

### ISSUE THREAD

**Issue by rafaelcapucho** [Yelp/docker-custodian#19]
Hello,

One of the problems I've is the size of this folder [1] increasing, When some execution fails on Mesos it is restarted by Marathon automatically, in a loop. And all dependency files are downloaded again and again.

I know that Custodian isn't directly related with Mesos/Marathon but if you use it you could offer a flag like --remove-mesos-residues.

[1] - /tmp/slaves/<slave-id>/frameworks/<fw-id>/executors

The Image attached is an example of restated failed app in a loop, and all those folders have the project resources downloaded again. It isn't an Custodian issue but a Enhancement Proposal.

![6](https://cloud.githubusercontent.com/assets/163367/10284285/a7a50156-6b59-11e5-96a8-0ae37e0ff569.png)

Thank you

**Comment by solarkennedy** [comment]
Cleaning up after mesos is outside the scope of docker-custodian.

I recommend:
- taking advantage of Marathon's exponential backoff 
- enabling disk space isolation 
- registering a disk space attribute for your slaves so mesos doesn't fill up your disks
- and if all else fails, tmpwatch'ing your sandbox directories here.
