### ISSUE TITLE
Add tag to yelp/docker-custodian on the docker hub

### ISSUE THREAD

**Issue by aidanhs** [Yelp/docker-custodian#21]
I note `dnephin/docker-custodian` (https://hub.docker.com/r/dnephin/docker-custodian/tags/) has a 0.5.0 tag but `yelp/docker-custodian` (https://hub.docker.com/r/yelp/docker-custodian/tags/) has none.

Any plans to add tags to this repo?

**Comment by solarkennedy** [comment]
Uh.. Hmm. I can probably manually add such a tag, but this is now a trusted-build, which only allows a single tag to be applied....

@dnephin do you have any suggestions? When someone makes a release they push to master, and then the docker build service builds the image. Do we have to manually tag that image after the fact?

**Comment by dnephin** [comment]
In https://hub.docker.com/r/yelp/docker-custodian/~/settings/automated-builds/ you can set other branches/tags to build and tag.

So if you git tag 0.5.1, and add that to the list of automated builds it will work (that's what I had setup).

**Comment by solarkennedy** [comment]
@dnephin but it sounds like I have to add each tag to the automated-builds interface as they are added? (I've add 0.5.0 and 0.5.1)

**Comment by dnephin** [comment]
Yup, I think that's right. There's an issue open for it (https://github.com/docker/hub-feedback/issues/165).

**Comment by dnephin** [comment]
Good news, the docker hub team just announced they are adding support for this feature next week!

>  This upgrade will offer dynamic matching of git branches and tags as well as faster builds.

**Comment by solarkennedy** [comment]
Nice!

**Comment by solarkennedy** [comment]
@aidanhs 0.5.1 is tagged and available on the hub.

**Comment by aidanhs** [comment]
Thanks!
