### ISSUE TITLE
Add ability to kill/delete running containers by age

### ISSUE THREAD

**Issue by analogue** [Yelp/docker-custodian#25]
For use cases where containers are only expected to run for a max amount of time, there is value in reaping running containers.  Don't know how this with mixin with the `--max-container-age option` - maybe `--max-running-container-age` as a completely separate option.

**Comment by dnephin** [comment]
This is what https://github.com/Yelp/docker-custodian#dcstop does.

**Comment by dnephin** [comment]
The prefix flag for `dcstop` is pretty old, I think #3 would make it more useful.

**Comment by analogue** [comment]
Ah, totally missed that. Labels is a nice way of tagging with max expected age.
