### ISSUE TITLE
backports.ssl-match-hostname>=3.5 error when running in Docker

### ISSUE THREAD

**Issue by keichan34** [Yelp/docker-custodian#37]
Using the currently published :latest tag on hub.docker.com results in:

```
$ docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock yelp/docker-custodian dcgc --help
Traceback (most recent call last):
  File "/usr/bin/dcgc", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: backports.ssl-match-hostname>=3.5
```

Checking the `v0.6.1` tag out and building locally works as expected. Maybe introduced in #36 ?

**Comment by zas** [comment]
Issue confirmed here, since #36 
The change at https://github.com/Yelp/docker-custodian/blob/d2cb9c467dfd193ce14e5deae7485b45898915d2/requirements.txt#L3 implies another change.
See https://github.com/docker/docker-py/blob/master/requirements.txt#L4

**Comment by solarkennedy** [comment]
Huh. Are the tests not good enough to catch this?

**Comment by solarkennedy** [comment]
@pauloconnor can you redo #36? I think the requirements.txt bump is incompatible with the existing stuff. I think the solution will be to activate a virtualenv and `pip install docker-py==1.81` and then do a pip-freeze to snapshot the new deps?

**Comment by matscederholm** [comment]
I ran into this one as well.

**Comment by solarkennedy** [comment]
The latest version of this image on the hub now works.

**Comment by matscederholm** [comment]
Like a charm!
