### ISSUE TITLE
Release Linux/ARM64 docker image for ‘Yelp/docker-custodian’

### ISSUE THREAD

**Issue by odidev** [Yelp/docker-custodian#57]
Hi Team,

I am interested in Linux/ARM64  ‘Yelp/docker-custodian’ docker image release.

I have built the docker image locally on a Linux/ARM64 machine, and it is building successfully with minor modification in dockerfile. 

Are you planning for the ARM64 docker image? If yes, I am happy to help and contribute. 

May I know what process you follow for building and releasing (CI/CD) the docker image to the docker hub?

**Comment by IamTheFij** [comment]
This is now available on the `master` tag. Will hopefully push out a new tagged version and update `latest` soon.

**Comment by IamTheFij** [comment]
Released as latest now.
